PopulateRefs unit test
The test fails on master with:

    WARNING: DATA RACE
    Read at 0x00c00038ccf8 by goroutine 10:
      k8s.io/apiserver/pkg/cel/openapi/resolver.populateRefs()
          /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/cel/openapi/resolver/refs.go:82 +0xb0a
      k8s.io/apiserver/pkg/cel/openapi/resolver.PopulateRefs()
          /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/cel/openapi/resolver/refs.go:37 +0x325
      k8s.io/apiserver/pkg/cel/openapi/resolver.TestPopulateRefs.func2()
          /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/cel/openapi/resolver/refs_test.go:99 +0x4f
      sync.(*WaitGroup).Go.func1()
          /nvme/gopath/go-1.25.2/src/sync/waitgroup.go:239 +0x5d

    Previous write at 0x00c00038ccf8 by goroutine 11:
      k8s.io/apiserver/pkg/cel/openapi/resolver.populateRefs()
          /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/cel/openapi/resolver/refs.go:89 +0xc1c
      k8s.io/apiserver/pkg/cel/openapi/resolver.PopulateRefs()
          /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/cel/openapi/resolver/refs.go:37 +0x325
      k8s.io/apiserver/pkg/cel/openapi/resolver.TestPopulateRefs.func3()
          /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/cel/openapi/resolver/refs_test.go:106 +0x3a
      sync.(*WaitGroup).Go.func1()
          /nvme/gopath/go-1.25.2/src/sync/waitgroup.go:239 +0x5d

    ...

    --- FAIL: TestPopulateRefs (0.00s)
        refs_test.go:115: read-only input schema got modified (- original, + modification):
              &spec.Schema{
              	VendorExtensible: {},
              	SchemaProps: spec.SchemaProps{
              		... // 22 identical fields
              		MinProperties: nil,
              		Required:      nil,
              		Items: &spec.SchemaOrArray{
              			Schema: &spec.Schema{
              				VendorExtensible: {},
              				SchemaProps: spec.SchemaProps{
            - 					ID: "",
            + 					ID: "item",
              					Ref: spec.Ref{
              						Ref: jsonreference.Ref{
              							... // 2 ignored fields
              							HasFullURL:      false,
            - 							HasURLPathOnly:  true,
            + 							HasURLPathOnly:  false,
              							HasFragmentOnly: false,
              							HasFileScheme:   false,
              							HasFullFilePath: false,
              						},
              					},
              					Schema:      "",
              					Description: "",
              					... // 31 identical fields
              				},
              				SwaggerSchemaProps: {},
              				ExtraProps:         nil,
              			},
              			Schemas: nil,
              		},
              		AllOf:      nil,
              		OneOf:      nil,
              		AnyOf:      nil,
              		Not:        nil,
              		Properties: {"a": {SchemaProps: {Ref: {Ref: {HasURLPathOnly: true, ...}}}}},
              		AdditionalProperties: &spec.SchemaOrBool{
              			Allows: false,
              			Schema: &spec.Schema{
              				VendorExtensible: {},
              				SchemaProps: spec.SchemaProps{
            - 					ID: "",
            + 					ID: "additional",
              					Ref: spec.Ref{
              						Ref: jsonreference.Ref{
              							... // 2 ignored fields
              							HasFullURL:      false,
            - 							HasURLPathOnly:  true,
            + 							HasURLPathOnly:  false,
              							HasFragmentOnly: false,
              							HasFileScheme:   false,
              							HasFullFilePath: false,
              						},
              					},
              					Schema:      "",
              					Description: "",
              					... // 31 identical fields
              				},
              				SwaggerSchemaProps: {},
              				ExtraProps:         nil,
              			},
              		},
              		PatternProperties: nil,
              		Dependencies:      nil,
              		... // 2 identical fields
              	},
              	SwaggerSchemaProps: {},
              	ExtraProps:         nil,
              }
        testing.go:1617: race detected during execution of test
    FAIL

Kubernetes-commit: ad7c5fda15224b35d92e0aeb6737e296a69fab91